services:
  - type: web
    name: collabcode-backend
    runtime: node
    rootDir: .
    buildCommand: npm install && npm run build
    startCommand: npm start --workspace=backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: MONGODB_URI
        sync: false
      - key: REDIS_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: https://collab-code-frontend-seven.vercel.app
      - key: DOCKER_SOCKET_PATH
        value: /var/run/docker.sock
